### ISSUE TITLE
[Ideas] Ideas for vuerd in future

### ISSUE THREAD

**Issue by peterstriz** [dineug/erd-editor#215]
I would like to ask you what you think of some ideas I would like to implement. Some are very easy and same may take longer and may change some functionality of vuerd.

- [x] (Idea) Have option to have diagram read-only so we could somehow show anybody how our GraphQL endpoints look like on live database

- [x] Make working with VSCode extension much easier - add some better communication that can be easily expanded

- [ ] [1 of 2] #212 

- [ ]  #213

- [x]  #214

**Comment by dineug** [comment]
1. There is a readonly option. `<erd-editor readonly></erd-editor>`

2. Let's also consider upgrading the VSCode extension environment.  
- For communication, it would be better to use GitHub discussions.
- I don't think real-time chatting will work well because I have to rely on a translator.

**Comment by dineug** [comment]
The vscode development environment has been improved.

```
$packages/vuerd yarn serve:vscode
# And
# Run Extension (vuerd-vscode)
```

**Comment by andrzejzysko** [comment]
What about generating table as HTML to put it in documentation like: Word, Confluence, etc? Maybe as `Generate Template`?

**Comment by oSethoum** [comment]
Hi, I would like if you add two more functions to the code generator, plural and singular so we can make code generation easier.
plural will pluralize English nouns.
singular does the opposite.

**Comment by the729** [comment]
Import from [DBML](https://www.dbml.org/)?

**Comment by oSethoum** [comment]
Add a way to add custom options for code generation, example am generation  a GraphQL API from vuerd json file, I would like to add sub: true to the columns I want to register them for subscriptions.

**Comment by filiscas** [comment]
It might be possible to hide the columns so they don't show up in the visualization
![image](https://user-images.githubusercontent.com/102948326/161494510-c021d533-a3d9-47ad-944e-4ac38dca8fd8.png)

**Comment by Androphin** [comment]
I second @the729 request and maybe also import from SQL DDL.
Another thought that came up my mind is live editing a remote database visually.
