### ISSUE TITLE
Multiple links to the same table generate an invalid graphql schema

### ISSUE THREAD

**Issue by PiTiLeZarD** [dineug/erd-editor#292]
Hi all,

First, thanks so much for the tool, it's been amazing to use and so helpful.

I've just noticed that when a table has 2 links to another one, the resulting graphql is invalid. Is there a way to control the generated name that I've missed or is there a bug here somewhere?

Here is what I mean with a screenshot:
![Screen Shot 2022-03-09 at 10 08 26 am](https://user-images.githubusercontent.com/5304/157347079-e9be5ef5-d979-4ac2-9df0-fa65df8e8c58.png)

Cheers

**Comment by dineug** [comment]
It has been modified in VS Code extension v2.0.4.
