### ISSUE TITLE
Git status change issue when scrolling on the screen

### ISSUE THREAD

**Issue by blaxk** [dineug/erd-editor#326]
In the `*.vuerd.json` file, there are `scrollTop: 1, scrollLeft: 1, zoomLevel: 1` item.
These values change when scrolling or zooming on the screen, so it's a good idea to separate them with a separate file.

ERD is managed by Git to share with co -developers.
Because of the scroll+zoom value of the `*.vuerd.json` file, the value changes just by scrolling the screen, and the git is recognized as a change state.

If you separate other values other than ERD settings into separate files, you can do `.gitignore` processing, so it is possible to manage the git change more effectively.

**Comment by theRightHooprod** [comment]
I'm with the same issue, it is hard to collaborate when the file keeps changing every time. I mean, instead of separate files it could be an option to deactivate this behavior.

**Comment by dineug** [comment]
I added options to vscode extension v1.0.20.
@theRightHooprod 
@blaxk 

<img width="519" alt="스크린샷 2024-04-13 오후 4 08 36" src="https://github.com/dineug/erd-editor/assets/45829489/cf1ccf91-9981-4add-b976-d9bbb4533b95">
