### ISSUE TITLE
Comments column re-size in Diagram

### ISSUE THREAD

**Issue by ikill69** [dineug/erd-editor#328]
Hi there ,

I am really impress with the plugin so thanks for all the hard work. 

For the life of me I can not work out how to increase the size of the comment column in the diagram view. It only shows about 16 Chars of the comment. 

I would like to be able to resize the table and the column to be bigger so that I can take useful screen shots for documentation.    

Could you please explain how I can do this if possible.

Thanks

**Comment by dineug** [comment]
New options have been added.
erd-editor-vscode v1.0.1
<img width="530" alt="스크린샷 2023-12-23 오전 8 02 16" src="https://github.com/dineug/erd-editor/assets/45829489/5959c804-da8b-48c9-83d3-a34a1d8af6c7">
