### ISSUE TITLE
An exception occurred when I was packaging the vuerd-vscode project

### ISSUE THREAD

**Issue by QuanZi123** [dineug/erd-editor#330]
node version: 18.3.0
npm version: 8.11.0
yarn version: 1.22.19

Pack command:   `vsce package`
Exception：  ` ERROR  invalid relative path: extension/../../.editorconfig`
![20230816105400395](https://github.com/dineug/erd-editor/assets/142292346/4c5bf0e9-3354-4402-9d6d-359eb14ddf8b)
How do I fix this exception？Thanks

**Comment by dineug** [comment]
main branch try again
