### ISSUE TITLE
Extension does not always save automatically

### ISSUE THREAD

**Issue by KFRANCMM** [dineug/erd-editor#333]
I don't know if this is a bug or if I need to use some option in the configuration. It has happened to me when I close the ERD Editor tab and all the changes are not saved, losing tables and relationships. 

Here is a recording of the problem
https://github.com/dineug/erd-editor/assets/26155050/c655a904-1785-4b3f-b508-b8d19cf02e8c

At first impression, the idea is to save the changes automatically, but this is not always the case. It's a great extension, one of my favorites but as a suggestion you could add a manual save button or fix the synchronization bug with the JSON file.

> **Extension**
> ERD Editor v0.9.15

> Version: 1.81.1 (user setup)
> Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
> Date: 2023-08-09T22:22:42.175Z
> Electron: 22.3.18
> ElectronBuildId: 22689846
> Chromium: 108.0.5359.215
> Node.js: 16.17.1
> V8: 10.8.168.25-electron.0
> OS: Windows_NT x64 10.0.22621

**Comment by OriCat101** [comment]
same issue here

**Comment by dineug** [comment]
erd-editor-vscode v1.0.1
try again

**Comment by mathursumit08** [comment]
I tested this and it works..Thank you so much for this update. This was a big issue for me as well :)
