### ISSUE TITLE
Pressing enter on selected dataType suggestion does nothing

### ISSUE THREAD

**Issue by spoco2** [dineug/erd-editor#334]
Loving the tool, however when I'm adding fields to tables, I type the column name, then start typing the dataType for the column, in this case `date`.

It start correctly autosuggesting dataTypes that match what I've typed. I can then arrow down through these options and _should_ be able to select one via pressing enter. 

However what actually happens is that I press enter on the highlighted dataType I want and it just closes the selection list and leaves the field with the partial text I've written, not completing it at all.

Mouse clicking on the item I want _does_ work as desired, but having to use the mouse is a lot slower than being able to do it all via keyboard.

I feel this isn't behaving as expected.

**Example 1**
Option Highlighted
<img width="360" alt="image" src="https://github.com/dineug/erd-editor/assets/5827872/e18ff474-468c-4093-8ec5-0c29f2550b32">

Press enter, get nothing updated in field
<img width="357" alt="image" src="https://github.com/dineug/erd-editor/assets/5827872/9308a7c3-534d-4455-8534-96037c90becf">

**Example 2**
Option Highlighted
<img width="353" alt="image" src="https://github.com/dineug/erd-editor/assets/5827872/b1c09521-0e1e-4dcc-93b0-f74656a0eb20">

Press enter, get nothing.
<img width="356" alt="image" src="https://github.com/dineug/erd-editor/assets/5827872/0b358090-9b6d-4175-8f34-febdf0f3f1d6">

This one shows how much of a time saver it would be to be able to type just `time` and then select `timestamp with time zone` rather than typing it all out, but it doesn't work.

**Comment by dineug** [comment]
Use the right arrow key #271

**Comment by spoco2** [comment]
Thanks for the reply. Not very intuitive, but thanks, I'll use this.
