### ISSUE TITLE
Diagram relationship paths have unnecessary cross overs

### ISSUE THREAD

**Issue by AMulgrave** [dineug/erd-editor#337]
The relationship paths are very sensitive to the position of tables
![image](https://github.com/dineug/erd-editor/assets/152357274/8c3e16db-ebf5-4aa3-b38f-9bd08c9b2f0a)

Moving a table up slightly
![image](https://github.com/dineug/erd-editor/assets/152357274/4bcdaa7d-4c25-4491-9a47-0a9a45d9c006)

will cause relationship paths to route with crossovers when there doesn't need to be.

**Comment by dineug** [comment]
Next version v3 will be modified. Please wait for me.

**Comment by dineug** [comment]
erd-editor-vscode v1.0.1 releases!
Migration
rename files with the extensions .vuerd and .vuerd.json to .erd and .erd.json respectively.

**Comment by AMulgrave** [comment]
updated to v1.0.7 thankyou for the improvements, while there is still some unexpected routing overall it is much better and easier to manually layout diagrams.
