### ISSUE TITLE
Allow hiding sidebar in erd-editor.io

### ISSUE THREAD

**Issue by jmatsushita** [dineug/erd-editor#356]
**Is your feature request related to a problem? Please describe.**
I like to have the editor open in a split screen configuration and in that case the left handside sidebar occupies a lot of real estate on screen whereas I'd like to have the schema in full focus.

**Describe the solution you'd like**
A button to allow hiding (and revealing) the left handside sidebar.

**Describe alternatives you've considered**
I work around this by adding `display: none` in the CSS with the devtools.

**Additional context**

![image](https://github.com/dineug/erd-editor/assets/356097/ef61d713-722b-487c-8f00-c642b7bd3d18)

**Comment by dineug** [comment]
I've added the feature and deployed it. Please refresh, and it should take effect in about 3 seconds.
