### ISSUE TITLE
How to AUTO_INCREMENT on mysql

### ISSUE THREAD

**Issue by theRightHooprod** [dineug/erd-editor#362]
**Is your feature request related to a problem? Please describe.**
I want to generate a table with AUTO_INCREMENT and I didn't know how. Is this feature already added to the project?.

**Describe the solution you'd like**
An option or work around of how to add AUTO_INCREMENT to my project in ERD-editor.

**Describe alternatives you've considered**
I considered adding it as a datatype, but it didn't work.

![Imagen de WhatsApp 2024-05-03 a las 12 41 05_1656e059](https://github.com/dineug/erd-editor/assets/60564900/f0bbdf6c-5b59-434b-bc61-f0eed76548e3)

When AUTO_INCREMENT is added like datatype on a PK... It's also modified at the FK.

**Additional context**
I'm working with AUTO_INREMENT primary keys.

**Comment by dineug** [comment]
Options are available.
<img width="437" alt="스크린샷 2024-05-04 오전 11 36 47" src="https://github.com/dineug/erd-editor/assets/45829489/a1860bc0-2b6e-451c-9c38-d4589e289d23">
