### ISSUE TITLE
Links from a table to itself are displayed incorrectly

### ISSUE THREAD

**Issue by developpeur-pro** [dineug/erd-editor#363]
**Describe the bug**
Links from a table to itself are displayed incorrectly (cf. capture below)

**To Reproduce**
Create a table with a foreign key to another column in the same table (eg: Employees.ReportsTo --> Employees.Id)

**Expected behavior**
Display the link correctly. Suggestion: this type of link could be systematically displayed with 4 angles in one corner of the table

**Screenshots**
Current:

![image](https://github.com/dineug/erd-editor/assets/16106898/a78d6a2a-3605-4327-ab67-ce2ed5b5a29c)

Expected:

![image](https://github.com/dineug/erd-editor/assets/16106898/bd10e534-8885-4397-ac38-3eecb7d0c7a3)

**Browser (please complete the following information):**

**VSCode (please complete the following information):**
 - OS: Windows 11
 - VSCode version: 1.89.1
 - Extension Version: 1.0.20

**Comment by dineug** [comment]
It has been modified in VS Code extension v2.0.4.
