### ISSUE TITLE
Unable open file.erd.json -166...

### ISSUE THREAD

**Issue by insidesecurity-yhojann-aguilera** [dineug/erd-editor#374]
**Describe the bug**
When try open my diagram created by this plugin for visual studio code says `Error no surch file or directory, open /home/user/.var/app/com.visualstudio.code/config/Code/User/workspaceStorage/9568.../dineug.vuerd-vscode/-1668366...`.

What is `-1668366...` file name?, attach a screenshot:

![Screenshot from 2024-07-19 15-21-43](https://github.com/user-attachments/assets/cc89b72f-0e95-4306-ad1f-75559cc037b3)

**To Reproduce**

I don't know exactly how to reproduce this error, I have a private diagram of a project and until I saved it there was no problem but now it doesn't want to load. I have no problems creating a new diagram, the problem is when it tries to open the existing one. I have not made any manual changes to this file, the computer where it is located is mine alone so no one else or any software could have made additional changes to it.

I try reinstall the plugin but does not work.

If you need any specific information from the diagram file, please let me know, I cannot publish it openly in this place as it contains confidential information.

**Browser:**
 - OS: GNU/Linux Ubuntu 22.04 LTS.
 - Browser Google Chrome
 - Version 126.0.6478.126 (Official Build) (64-bit) (flatpak)

**VSCode:**
 - OS: GNU/Linux Ubuntu 22.04 LTS.
 - VSCode version: 1.90.2 (flatpak)
 - Extension Version: 1.0.20

**Comment by insidesecurity-yhojann-aguilera** [comment]
I try delete parts of `.erd.json` file and try load again in visual studio but I ended up deleting almost all the content without even being able to open it, I realized that the problem is not the file with its content but a problem with the file path, I have changed the name and it has loaded correctly, but why does it happen? This is not a problem with access to the json file, it is not a permissions problem or anything, could it be a problem in the webcache of the webkit engine in visual studio?

Maybe there is some configuration of the plugin that is corrupting access to the diagram, if I rename the file to the original name it cannot open it again, throwing the same error again. Please review how the configurations related to the open diagram files are being saved.

**Comment by dineug** [comment]
VSCode has a backup process for cases when files are closed without saving. The backup path seems to be managed by VSCode, but it appears that it was deleted by an external factor.

It seems that the integrity of the backup information managed by VSCode has been compromised. Therefore, it looks necessary to cleanly delete all VSCode-related caches and perform a fresh reinstallation.

https://github.com/dineug/erd-editor/blob/e1c685ea5d72b509174461b2f03039cef3070dde/packages/erd-editor-vscode/src/erd-editor-provider.ts#L44
