### ISSUE TITLE
Relations on column level

### ISSUE THREAD

**Issue by gulivan** [dineug/erd-editor#378]
Thank you for an amazing tool, it's very neat!

Pls consider to display relationships between primary and foreign keys on the column level.

**Comment by dineug** [comment]
I'm already displaying it, so which feature are you referring to?
<img width="304" alt="스크린샷 2024-10-16 203528" src="https://github.com/user-attachments/assets/a50a1fc3-ecc6-41be-8622-99867a30967c">

**Comment by gulivan** [comment]
I believe that in the current implementation, relationships are shown at the table level but not at the column level.

**Comment by dineug** [comment]
Could you provide a simple example of column-level display?

**Comment by gulivan** [comment]
from dbdiagram:
<img width="681" alt="image" src="https://github.com/user-attachments/assets/526ce38c-a0b6-4e46-af8e-28898d02fa0e">

**Comment by dineug** [comment]
I understand! Thank you.

**Comment by dineug** [comment]
Modified in VSCode extension v2.0.2
The column key works when hovered.
